<a href="https://colab.research.google.com/github/norightt/python-machine-learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [ ]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [ ]:
!wget https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
!unzip /content/Data.zip

--2024-02-09 08:26:48--  https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip [following]
--2024-02-09 08:26:48--  https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16727 (16K) [application/zip]
Saving to: ‘Data.zip’

Data.zip            100%[===================>]  16.33K  --.-KB/s    in 0s

2024-02-09 08:26:48 (85.2 MB/s) - ‘Data.zip’ saved [16727/16727]

Archive:  /content/Data.zip
   creating: Data/
  inflating: Data/Students_info_0.csv
  inflating: Data/Students_info_1.csv
  inflating: Data/Students_info_2.csv
  inflating: Data/Students_info_3.csv
  inflating: Data/Students_info_4.csv
  inflating: Data/Students_info_5.csv
  inflating: Data/Students_info_6.csv
  inflating: Data/Students_info_7.csv
  inflating: Data/Students_info_8.csv
  inflating: Data/Students_info_9.csv
  inflating: Data/Students_marks_0.csv
  inflating: Data/Students_marks_1.csv
  inflating: Data/Students_marks_2.csv
  inflating: Data/Students_marks_3.csv
  inflating: Data/Students_marks_4.csv
  inflating: Data/Students_marks_5.csv
  inflating: Data/Students_marks_6.csv
  inflating: Data/Students_marks_7.csv
  inflating: Data/Students_marks_8.csv
  inflating: Data/Students_marks_9.csv

Для начала, нужно создать лист с названиями всех файлов из zip с помощью .namelist().

In [ ]:
import zipfile
zip_file = zipfile.ZipFile('/content/Data.zip', 'r')
file_names = zip_file.namelist()

Затем создаем два датафрейма из файлов с info и marks.

In [ ]:
info_list = []

for filik in file_names[1:11]:
  df1 = pd.read_csv(filik)
  info_list.append(df1)

df_info = pd.concat(info_list, axis = 0)

In [ ]:
marks_list = []

for filik in file_names[11:]:
  df2 = pd.read_csv(filik)
  marks_list.append(df2)

df_marks = pd.concat(marks_list, axis = 0)

И объединяем два датафрейма по колонке index, в итоге поолучается датафрейм со всей имеющийся информацией о студентах.

In [ ]:
df = pd.merge(df_info, df_marks, on="index")

In [ ]:
df.head(10)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
5,5,female,group B,associate's degree,standard,none,group1,71,83,78
6,6,female,group B,some college,standard,completed,group1,88,95,92
7,7,male,group B,some college,free/reduced,none,group1,40,43,39
8,8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
df = df.drop("index", axis=1)

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

Нет пропущенных значений.

In [ ]:
df.isnull().values.any()

False

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
df[["math score", "reading score", "writing score"]].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

Студенты, прошедшие подготовительные курсы, в среднем набрали больше баллов по всем трем предметам.

In [ ]:
df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df.rename(columns = {"parental level of education": "education", "test preparation course": "test preparation"}, inplace=True)

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

Доля студентов сдавших экзамен по матиматике - 86.5%

In [ ]:
pass_math = df[df['math score'] >= passmark]
share_pass_math = len(pass_math) / len(df)
share_pass_math * 100

86.5

 Доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике - 92.2%

In [ ]:
course_pass = df.query('`math score` >= @passmark & `test preparation` == "completed"')
course_compl = df.query('`test preparation` == "completed"')
share_course_pass = len(course_pass) / len(course_compl)
round(share_course_pass * 100, 1)

92.2

Доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике - 21%

In [ ]:
women_nopass = df.query('gender == "female" & `math score` < @passmark & `test preparation` == "none"')
women_nocourse = df.query('gender == "female" & `test preparation` == "none"')
share_women_nopass = len(women_nopass) / len(women_nocourse)
round(share_women_nopass * 100, 1)

21.0

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
df.groupby('race/ethnicity')['reading score'].mean()

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [ ]:
%%timeit
df.groupby('race/ethnicity')['reading score'].mean()

622 µs ± 104 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [ ]:
df.groupby('education')['writing score'].min()

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

In [ ]:
%%timeit
df.groupby('education')['writing score'].min()

668 µs ± 106 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

С помощю циклов операции выполняются медленнее.

In [ ]:
%%timeit
ethnic_groups = df['race/ethnicity'].unique()

avg_reading_scores = {}

for group in ethnic_groups:
    avg_score = df[df['race/ethnicity'] == group]['reading score'].mean()
    avg_reading_scores[group] = avg_score

dict(sorted(avg_reading_scores.items()))

2.77 ms ± 78.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [ ]:
%%timeit
education_levels = df['education'].unique()

avg_writing_score = {}

for level in education_levels:
  avg_score = df[df['education'] == level]['writing score'].min()
  avg_writing_score[level] = avg_score

dict(sorted(avg_writing_score.items()))

3.1 ms ± 41.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [ ]:
import numpy as np

In [ ]:
grouped = pd.pivot_table(df, index=['gender', 'education'],values=['math score', 'reading score', 'writing score'], aggfunc= np.mean)
grouped

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
df['Math_PassStatus'] = np.where(df['math score']>= passmark, "P", "F")
df.head(10)

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P
1,female,group C,some college,standard,completed,group1,69,90,88,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F
4,male,group C,some college,standard,none,group1,76,78,75,P
5,female,group B,associate's degree,standard,none,group1,71,83,78,P
6,female,group B,some college,standard,completed,group1,88,95,92,P
7,male,group B,some college,free/reduced,none,group1,40,43,39,F
8,male,group D,high school,free/reduced,completed,group1,64,64,67,P
9,female,group B,high school,free/reduced,none,group1,38,60,50,F

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
df['OverAll_PassStatus'] = np.where((df['math score'] < passmark) | (df['reading score'] < passmark) | (df['writing score'] < passmark), "F", "P")
df.head(10)

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P
5,female,group B,associate's degree,standard,none,group1,71,83,78,P,P
6,female,group B,some college,standard,completed,group1,88,95,92,P,P
7,male,group B,some college,free/reduced,none,group1,40,43,39,F,F
8,male,group D,high school,free/reduced,completed,group1,64,64,67,P,P
9,female,group B,high school,free/reduced,none,group1,38,60,50,F,F

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [ ]:
def GetGrade(average_mark):
    if average_mark >= 90:
        return "A"
    elif 80 <= average_mark < 90:
        return "B"
    elif 70 <= average_mark < 80:
        return "C"
    elif 60 <= average_mark < 70:
        return "D"
    elif 50 <= average_mark < 60:
        return "E"
    else:
        return "F"

df['average_mark'] = (df['math score'] + df['reading score'] + df['writing score']) / 3

df['Grade'] = df['average_mark'].apply(GetGrade)

df = df.drop("average_mark", axis=1)

In [ ]:
df['Grade'].value_counts()

C    261
D    256
E    182
B    146
F    103
A     52
Name: Grade, dtype: int64